
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'DBC8FE2883BF679079BF071DCE395C5B'
    
_lr_action_items = {'FALSE':([0,2,4,5,7,8,13,14,16,17,18,21,23,25,26,27,28,33,35,38,40,],[5,-24,-20,-23,-17,-19,-18,-22,-5,5,5,5,-11,5,-12,-10,-13,-6,-16,-14,-15,]),'NIL':([0,2,4,5,7,8,13,14,16,17,18,23,25,26,27,28,33,35,38,40,],[2,-24,-20,-23,-17,-19,-18,-22,-5,2,2,-11,2,-12,-10,-13,-6,-16,-14,-15,]),'TEXT':([0,2,4,5,7,8,13,14,16,17,18,23,25,26,27,28,33,35,38,40,],[4,-24,-20,-23,-17,-19,-18,-22,-5,4,4,-11,4,-12,-10,-13,-6,-16,-14,-15,]),'SIMB':([0,2,4,5,7,8,11,13,14,15,16,17,18,19,23,25,26,27,28,33,35,38,40,],[7,-24,-20,-23,-17,-19,18,-18,-22,22,-5,7,7,18,-11,7,-12,-10,-13,-6,-16,-14,-15,]),'NUM':([0,2,4,5,7,8,13,14,16,17,18,22,23,25,26,27,28,31,33,35,37,38,40,],[8,-24,-20,-23,-17,-19,-18,-22,-5,8,8,32,-11,8,-12,-10,-13,37,-6,-16,39,-14,-15,]),'LET':([0,2,4,5,7,8,11,13,14,16,17,18,20,23,25,26,27,28,33,35,38,40,],[6,-24,-20,-23,-17,-19,6,-18,-22,-5,6,6,6,-11,6,-12,-10,-13,-6,-16,-14,-15,]),'LPAREN':([0,2,4,5,6,7,8,10,11,13,14,16,17,18,20,23,25,26,27,28,33,35,38,40,],[11,-24,-20,-23,15,-17,-19,17,19,-18,-22,-5,19,19,19,-11,19,-12,-10,-13,-6,-16,-14,-15,]),'QUOTE':([0,2,4,5,7,8,13,14,16,17,18,23,25,26,27,28,33,35,38,40,],[10,-24,-20,-23,-17,-19,-18,-22,-5,10,10,-11,10,-12,-10,-13,-6,-16,-14,-15,]),'RPAREN':([2,4,5,7,8,13,14,16,17,18,23,24,25,26,27,28,29,30,32,33,34,35,38,39,40,],[-24,-20,-23,-17,-19,-18,-22,-5,-9,-9,-11,33,-9,-12,-10,-8,35,36,38,-6,-7,-16,-14,40,-15,]),'IF':([11,19,],[21,21,]),'TRUE':([0,2,4,5,7,8,13,14,16,17,18,21,23,25,26,27,28,33,35,38,40,],[14,-24,-20,-23,-17,-19,-18,-22,-5,14,14,14,-11,14,-12,-10,-13,-6,-16,-14,-15,]),'$end':([0,1,2,3,4,5,7,8,9,12,13,14,16,33,35,36,38,40,],[-21,0,-24,-2,-20,-23,-17,-19,-4,-1,-18,-22,-5,-6,-16,-3,-14,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'quoted_list':([0,17,18,25,],[3,23,23,23,]),'items':([17,18,25,],[24,29,34,]),'list':([10,],[16,]),'item':([17,18,25,],[25,25,25,]),'bool':([0,17,18,21,25,],[13,13,13,31,13,]),'exp':([0,],[1,]),'atom':([0,17,18,25,],[12,27,27,27,]),'call':([0,11,17,18,20,25,],[9,20,26,26,30,26,]),'empty':([17,18,25,],[28,28,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> atom','exp',1,'p_exp_atom','yacc.py',150),
  ('exp -> quoted_list','exp',1,'p_exp_qlist','yacc.py',154),
  ('exp -> LPAREN call call RPAREN','exp',4,'p_exp_doublecall','yacc.py',160),
  ('exp -> call','exp',1,'p_exp_call','yacc.py',166),
  ('quoted_list -> QUOTE list','quoted_list',2,'p_quoted_list','yacc.py',170),
  ('list -> LPAREN items RPAREN','list',3,'p_list','yacc.py',174),
  ('items -> item items','items',2,'p_items','yacc.py',178),
  ('items -> empty','items',1,'p_items_empty','yacc.py',182),
  ('empty -> <empty>','empty',0,'p_empty','yacc.py',186),
  ('item -> atom','item',1,'p_item_atom','yacc.py',190),
  ('item -> quoted_list','item',1,'p_item_list','yacc.py',198),
  ('item -> call','item',1,'p_item_call','yacc.py',202),
  ('item -> empty','item',1,'p_item_empty','yacc.py',206),
  ('call -> LET LPAREN SIMB NUM RPAREN','call',5,'p_let','yacc.py',213),
  ('call -> LPAREN IF bool NUM NUM RPAREN','call',6,'p_if','yacc.py',217),
  ('call -> LPAREN SIMB items RPAREN','call',4,'p_call','yacc.py',224),
  ('atom -> SIMB','atom',1,'p_atom_simbol','yacc.py',230),
  ('atom -> bool','atom',1,'p_atom_bool','yacc.py',237),
  ('atom -> NUM','atom',1,'p_atom_num','yacc.py',241),
  ('atom -> TEXT','atom',1,'p_atom_word','yacc.py',245),
  ('atom -> <empty>','atom',0,'p_atom_empty','yacc.py',249),
  ('bool -> TRUE','bool',1,'p_true','yacc.py',253),
  ('bool -> FALSE','bool',1,'p_false','yacc.py',257),
  ('atom -> NIL','atom',1,'p_nil','yacc.py',261),
]
